NoteTakingApp/NoteTakingApp.WebApp/Models/CreatedNote.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using NoteTakingApp.Domain;

namespace NoteTakingApp.WebApp.Models
{
    public class CreatedNote //: IValidatableObject
    {
        [Required]
        [MinLength(3)]
        public string Text { get; set; }

        public List<string> Tags { get; set; }

        //public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        //{
        //    //var repo = validationContext.GetService(typeof(IRepository));
        //    //repo.
        //}

        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }
    }
}

NoteTakingApp/NoteTakingApp.WebApp/Models/ErrorViewModel.cs
using System;

namespace NoteTakingApp.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NoteTakingApp/NoteTakingApp.WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NoteTakingApp.Domain;
using NoteTakingApp.WebApp.Models;

namespace NoteTakingApp.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IRepository _repo;

        public HomeController(ILogger<HomeController> logger, IRepository repo)
        {
            _logger = logger;
            _repo = repo;
        }

        public IActionResult Index(string texttoprint)
        {
            var notes = _repo.GetNotes();
            // ways to get data from controller to the view:
            //  - pass an object as the "model" parameter of the View method.
            //       it is visible as "Model" within the view.
            //  - ViewData (dictionary of string to object)
            //  - also, ViewBag and TempData

            // views can have a @model directive at the top,
            // making them "strongly-typed" as opposed to dynamically/weakly-typed.
            // - meaning, you have to pass the right data type of object to the view.

            // web developers culturally prefer dynamically typed stuff more
            // so than backend developers
            ViewBag.key = texttoprint;
            ViewData["note"] = new Note { Id = -5, Text = "asdf" };

            TempData["note"] = JsonSerializer.Serialize(ViewData["note"]);
            JsonSerializer.Deserialize<Note>((string)TempData["note"]);
            // TempData is meant for small pieces of data
            // which are discarded as soon as you're done with them
            
            if (!TempData.ContainsKey("viewTracker"))
            {
                TempData["viewTracker"] = 1;
            }
            else
            {
                TempData["viewTracker"] = (int)TempData["viewTracker"] + 1;
            }

            return View(model: notes);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NoteTakingApp/NoteTakingApp.WebApp/Controllers/NoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage;
using NoteTakingApp.Domain;
using NoteTakingApp.WebApp.Models;

namespace NoteTakingApp.WebApp.Controllers
{
    public class NoteController : Controller
    {
        private readonly IRepository _repo;

        public NoteController(IRepository repo)
        {
            _repo = repo;
        }

        public IActionResult Index()
        {
            return View(_repo.GetNotes());
        }

        public IActionResult Details(int id)
        {
            // bad: should have a repo implementation to just get one note
            return View(_repo.GetNotes().First(x => x.Id == id));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost] // form submission (by default)
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreatedNote viewModel)
        {
            // ASP.NET "model binding"
            // - fill in action method parameters with data from the request
            //   (URL path, URL query string, form data, etc.)
            //   based on compatible data type and name.

            // validate all action method parameters as user input
            if (!ModelState.IsValid)
            {
                // if ModelState has errors, that can influence view rendering
                // (the validation tag helpers look at it)
                return View(viewModel);
                //return View("ErrorMessage", model: "invalid");
            }

            var note = new Note { Text = viewModel.Text };

            try
            {
                _repo.AddNote(note);
            }
            catch (InvalidOperationException e)
            {
                ModelState.AddModelError(key: "Text", errorMessage: e.Message);
                ModelState.AddModelError(key: "", errorMessage: "general errors could go up here");
                return View(viewModel);
            }

            //return View("Details", note);
            return RedirectToAction("Details", new { id = note.Id });
        }
    }
}

NoteTakingApp/NoteTakingApp.WebApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace NoteTakingApp.WebApp.Controllers
{
    public class UserController : Controller
    {
        // GET: UserController
        public ActionResult Index()
        {
            return View();
        }

        // GET: UserController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UserController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UserController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

NoteTakingApp/NoteTakingApp.WebApp/Views/Home/Index.cshtml
@model IEnumerable<NoteTakingApp.Domain.Note>

@{
  ViewData["Title"] = "Home Page";
}

<div class="text-center">
  <h1 class="display-4">Welcome</h1>
</div>

<div>@ViewData["key"]</div>
<div>@(((NoteTakingApp.Domain.Note)ViewData["note"]).Id)</div>
<div>@ViewBag.note.Id</div>

<div><a asp-action="Index" asp-route-id="hello">link 1</a></div>
<div><a asp-action="Index" asp-route-texttoprint="hello">link 2</a></div>

@* every time you access something in tempdata using the indexing operator [],
  that key-value pair is marked for being deleted at the end of this request. *@
@* use methods Keep and Peek to explicitly keep the data around longer. *@
<div>views: @TempData.Peek("viewTracker")</div>

<table>
  <thead>
    <tr>
      <th>Note text</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var note in Model)
    {
      <tr>
        <td>@note.Text</td>
      </tr>
    }
  </tbody>
</table>

NoteTakingApp/NoteTakingApp.WebApp/Views/Note/Create.cshtml
@model CreatedNote

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Note</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NoteTakingApp/NoteTakingApp.WebApp/Views/Note/Details.cshtml
@model NoteTakingApp.Domain.Note

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Note</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WordCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WordCount)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

NoteTakingApp/NoteTakingApp.WebApp/Views/Note/Index.cshtml
@model IEnumerable<NoteTakingApp.Domain.Note>

@{
  ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
  <a asp-action="Create">Create New</a>
</p>
<table class="table">
  <thead>
    <tr>
      <th>
        @Html.DisplayNameFor(model => model.Id)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Text)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.WordCount)
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    @foreach (var item in Model)
    {
      <tr>
        <td>
          @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.WordCount)
        </td>
        <td>
          @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
          @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
          @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
      </tr>
    }
  </tbody>
</table>

NoteTakingApp/NoteTakingApp.WebApp/Views/Shared/ErrorMessage.cshtml
@model string

<p>Error</p>
<p>@Model</p>

NoteTakingApp/NoteTakingApp.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NoteTakingApp.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
      <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NoteTakingApp.WebApp</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
          <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="Index">Notes</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <div class="container">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
    @*<aside>
        @RenderSection("Sidebar")
      </aside>*@
  </div>

  <footer class="border-top footer text-muted">
    <div class="container">
      &copy; 2021 - NoteTakingApp.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
  </footer>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>